config/routes.rb
Ferret::Application.routes.draw do

  root to: 'static_pages#home'

  get '/help',  to: 'static_pages#help'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = 'Ferret'
    if page_title.empty?
      base_title
    else
      "#{ page_title } | #{ base_title }"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <ul>
    <li><%= link_to 'About', '#' %></li>
    <li><%= link_to 'Contact', '#' %></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'Ferret', root_path, id: 'logo' %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Help', help_path %></li>
	  <!--Uh huh well this will be integrated with
	      devise so if some one is logged in it will
	       put their name and shit but for now eh -->
	  <li><%= link_to 'Sign In', '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Help page goes here!
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Ferret</h1>
  <p>
    Ferret is a centralized platform for FRC scouting
  </p>

  <%= link_to 'Sign Up', '#', class: 'btn btn-large btn-primary' %>
</div>